### ISSUE TITLE
Integrate with mattermost

### ISSUE THREAD

**Issue by alexdor** [techministry/MinisterIN#24]
Integrate consuela to chat.lambdaspace.gr in order to announce space status updates and upcoming events.

**Comment by alexdor** [comment]
@AEtherC0r3 any thoughts on this?

**Comment by AEtherC0r3** [comment]
It is doable and probably relatively easy
So, yeah, let's do it

We can probably utilize incoming web hooks to do it https://docs.mattermost.com/developer/webhooks-incoming.html

**Comment by alexdor** [comment]
Added with 01ac86d13a393a1637133271a8735a7d5f545039
